package-lock.json, package.json, public/assets/images/img_black.svg, public/assets/images/img_check.svg, src/components/DeleteModal.jsx, src/components/DeleteModal.module.css
=> [김민서] DeleteModal 컴포넌트

public/assets/icons/ic_meatballs_menu.svg, src/components/challenge/AllCardSection.jsx, src/components/challenge/AllCardSection.module.css, src/components/challenge/Card.jsx, src/components/challenge/Card.module.css, src/pages/index.js, src/pages/me/done/index.jsx, src/pages/me/index.jsx, src/variables/images.js
=> [이율리] Challenge 컴포넌트 생성 및 생성된 컴포넌트들 전체 연결

src/components/application/ChallengeStatusBadge.jsx, src/components/application/ChallengeStatusBadge.module.css, src/components/application/ChallengeTable.jsx, src/components/application/ChallengeTable.module.css, src/components/challenge/InfoContainer.jsx, src/components/challenge/InfoContainer.module.css, src/components/common/DocTypeChip.jsx, src/components/layouts/Layout.module.css, src/pages/application/index.jsx, src/pages/me/application/[id].jsx, src/pages/me/application/index.jsx, src/styles/globals.css, src/styles/pages/application/MyApplicationDetailPage.module.css
=> [김민서] 신청한 챌린지 상세 페이지

src/components/challenge/AllCardSection.jsx, src/components/common/ChallengeSearchBarLarge.jsx, src/components/common/Profile.jsx, src/components/layouts/Headers.jsx, src/components/layouts/Headers.module.css, src/components/layouts/Layout.jsx, src/components/layouts/ProfileDropDown.jsx, src/components/user/LoginForm.jsx, src/components/user/SignUpForm.jsx, src/context/AuthProvider.js, src/hooks/useAuth.js, src/pages/auth/login.jsx, src/service/api/axios.js
=> [임송이] 로그인 회원가입 오류 수정

src/components/challenge/AllCardSection.jsx, src/components/common/KebabMenu.jsx, src/components/layouts/Layout.jsx, src/components/layouts/ProfileDropDown.jsx, src/context/AuthProvider.js, src/hooks/useAuth.js, src/hooks/useModal.js, src/pages/index.js, src/service/api/auth.js, src/service/api/axios.js, src/service/api/challenge.js, src/service/queries/challenge.js
=> [임송이] 로그아웃 오류 수정

mockup/challenge.js, src/components/challenge/AllCardSection.jsx, src/pages/index.js, src/pages/me/done/index.jsx, src/pages/me/index.jsx
=> Feature/page challenge 이율리

src/components/common/Button.jsx, src/components/common/Button.module.css, src/components/feedback/UpdatedFeedbackForm.jsx, src/components/layouts/Layout.module.css, src/pages/work/[id].jsx
**출처: Button.js**
**props: 기본 props 설정.**
```jsx
variant = 'black',
disabled = false,
onClick,
type = 'button',
className = '',
borderRadius = '12px',
width = '',
height = '',
padding = '',
fontSize = '16px',
fontWeight = '600',
```
**종류: varient**
```jsx
<Button variant="black">블랙 </Button>
<Button variant="yellow">옐로우 </Button>
<Button variant="yellow-border">옐로우보더 </Button>
<Button variant="white-border">화이트보더 </Button>
```
*기본적으로 설정되어있는 CSS는 아래와 같아요.
(스타일별 :hover 되어있음)
```css
.button {
padding: 11px 48.5px;
font: 16px;
font-weight: 600;
}
```
비활성화 시
```jsx
<Button variant="white-border" disabled={true}>
비활성화 </Button>
```
**예시:** 조정이 필요하다면 props를 내려주시면 됩니다. (className 내려셔서 상위 컴포넌트 모듈에서 스타일 하셔도 돼요 :)
```jsx
<Button
borderRadius="8px"
width="150px"
height="50px"
padding="10px 20px" …
```
=> [임송이] Button 공통 컴포넌트

src/components/application/ChallengeTable.jsx, src/components/common/CancelMenu.jsx, src/components/common/CancelMenu.module.css, src/pages/application/index.jsx, src/pages/me/application/[id].jsx, src/pages/me/application/index.jsx, src/service/api/axios.js, src/service/api/challenge.js, src/service/api/user.js
- 지금까지 구현한 페이지에 대한 데이터 연동을 완료하였습니다. (챌린지 수정 페이지는 어드민 전용이므로 다음 PR에서 처리할 예정입니다.)
=> [김민서] 신청한 챌린지 페이지,  신청한 챌린지 상세 조회 페이지, 신규 챌린지 신청하기 페이지에 API 연동

src/service/api/axios.js
- 에러핸들링 관련입니다
- 전체적인 flow 보기가 조금 애매해서 일단 이거만 수정했는데 추가적으로 수정해볼수도있을거같습니다
=> [김현우] axios instance 핸들링 관련

src/pages/work/new.jsx, src/service/api/axios.js
=> ♻ [Refactor] 에러핸들링 관련

src/components/work/EditorToolbar.jsx, src/components/work/TextEditor.jsx
React-Quill implementation
Dynamic으로 SSR 오류 수정.
배포 시도용 커밋
=> :sparkles: [Feat] implement React-Quill

next.config.mjs, package-lock.json, package.json, src/components/feedback/FeedbackContent.jsx, src/components/feedback/FeedbackContent.module.css, src/components/feedback/FeedbackForm.module.css, src/components/feedback/RepliesList.jsx, src/components/feedback/Reply.jsx, src/components/feedback/UpdateFeedbackForm.module.css, src/components/layouts/ProfileDropDown.jsx, src/hooks/useAuth.js, src/service/api/axios.js, src/service/api/feedback.js, src/service/mutations/feedback.js, src/variables/queryKeys.js
- Auth관련 Refactor
- 대댓글 기능 추가
- 대댓글, 댓글 디자인 세부수정 예정
- 오류 말씀주시면 수정하겠습니다
=> [김현우] 대댓글 기능 추가 및 Auth 기능 관련 refactor

src/components/layouts/Layout.jsx
=> [김현우] layout fix

src/components/common/LikeButton.jsx, src/components/work/TextEditor.jsx, src/components/work/WorkDetail.jsx, src/pages/[id].jsx, src/pages/work/[id]/index.jsx, src/pages/work/new/[id].jsx, src/service/api/axios.js, src/service/api/challenge.js, src/service/api/work.js, src/service/mutations/challenge.js, src/service/mutations/work.js, src/service/queries/challenge.js, src/service/queries/work.js, src/variables/queryKeys.js
=> [임송이] 작업물 상세페이지 좋아요 버튼 및 api 추가

src/components/mypage/edit.jsx, src/components/mypage/edit.module.css
=> [김민수] : 마이페이지 버튼

src/pages/[id].jsx
=> [김현우] 버그관련

src/components/application/AdminModal.jsx, src/components/application/AdminModal.module.css, src/components/application/ChallengeTable.module.css, src/components/user/userForms.module.css
=> [김민서] 페이지 디테일 수정

src/components/feedback/FeedbackContent.jsx, src/components/feedback/FeedbackList.jsx, src/components/feedback/RepliesList.jsx, src/components/feedback/Reply.jsx, src/components/work/WorkDetail.jsx, src/pages/profile/[id].jsx, src/pages/profile/edit/index.jsx, src/pages/profile/index.jsx, src/service/mutations/feedback.js, src/service/queries/work.js
=> [임송이] :bug: [Fix] Feedback Reply API 구분 및 쿼리 조정 invalidate

src/components/challenge/Card.jsx, src/components/mypage/MyPageChallengeButton.jsx
…쓰기 수정
- 마이페이지 챌린지 4개일 경우 안 버튼 안 눌리는 부분 수정, card-bottom css 띄어쓰로 인해 적용 안 되는 부분 수정
=> [김효인] 버그 수정

src/pages/profile/[id].jsx
=> [김효인] css 참조 오류 수정

src/components/challenge/Container.jsx
=> [이율리] 챌린지 상세 페이지 수정
